package us.mude.common;

public enum AwardType {
    ENUM_ORDINAL_0,
    BEST_PICTURE,
    DIRECTING,
    BEST_ACTOR_IN_A_LEADING_ROLE,
    BEST_ACTRESS_IN_A_LEADING_ROLE,
    BEST_ACTOR_IN_A_SUPPORTING_ROLE,
    BEST_ACTRESS_IN_A_SUPPORTING_ROLE
}
